### ISSUE TITLE
Bom Dia, gostaria de entrar para o time

### ISSUE THREAD

**Issue by rafaelgurgel** [thr0w/idvogados#10]
Gostaria de me juntar à equipe de desenvolvimento, sou programador (foco Ruby/Backend + JS/HTML/CSS Frontend). Infelizmente não posso mostrar o que faço devido à NDA´s.
LinkedIn: https://www.linkedin.com/in/rafaelgurgelbr/

**Comment by teintinu** [comment]
Bom dia @rafaelgurgel , Bem vindo! Os fontes estão ai. Pode clonar o repositório e contribuir com o que você puder.
Abraço!
