### ISSUE TITLE
Typos no Readme

### ISSUE THREAD

**Issue by leoheck** [thr0w/idvogados#12]
Trechos pra arrumar

> "Materei" esse projeto por um tempo...

> a auxiliar com que a "propsota" do

> Você pode usar esse "projeot" ou trechos...

> desse app é apenas de "facilitadr" o

**Comment by leoheck** [comment]
Não entendo a necessidade de usar `o(a)`. Mesmo assim, seguindo, tu pode adicionar ai na trabalhadora que faltou.

> Facilitar a(o) trabalhadora

**Comment by teintinu** [comment]
Corrigi. Obrigado.
