### ISSUE TITLE
Link do Slack nos comentários do vídeo do greg news expirou, como participo?

### ISSUE THREAD

**Issue by GabrielPaliari** [thr0w/idvogados#5]
Sou programador front end React. Quero saber se esse projeto está relacionado com o grupo do slack que foi referenciado nos comentários do vídeo do greg news. Se sim, gostaria de entrar no grupo e saber qual a melhor forma de auxiliar, quais são as próximas features, etc.

**Comment by teintinu** [comment]
Oi Gabriel, não sei. Eu não controlo lá.

**Comment by gBritz** [comment]
@GabrielPaliari parece que o `Alex Guimarães` criou um grupo no facebook para organizar, acesse:
https://www.facebook.com/groups/idvogados/permalink/219794142800877
