### ISSUE TITLE
Tem um grupo no Slack com a mesma proposta.

### ISSUE THREAD

**Issue by Zenguen** [thr0w/idvogados#7]
Contam 760 membros no grupo.
Hoje dia 19/04/2020 às 14 h vai haver uma reunião para definir o MVP (Produto Mínimo Viável).
Segue o link:
https://join.slack.com/t/idvogados/shared_invite/zt-doceruir-6lC5K0KREQCR~hvGz7u0Rg

**Comment by timoteo7** [comment]
E também com um repositório paralelo

https://github.com/idvogados/idvogados

- https://join.slack.com/t/idvogados/shared_invite/zt-doceruir-6lC5K0KREQCR~hvGz7u0Rg
- https://docs.google.com/presentation/d/1FMjad0AfBszs8JreUAjSCjJ8hPMkFhm-iIQU59FTM_M/edit#slide=id.p
- https://www.youtube.com/watch?v=S8EqXuzjsL8

**Comment by teintinu** [comment]
Bom demais! Eu não consigo participar do grupo! É muita conversa e meu tempo é pouco pra acompanhar. Mas desejo sucesso ao grupo. Vou continuar rascunhando aqui, se o grupo quiser minha contribuição, é só chamar.
