### ISSUE TITLE
Programador(a) TypeScript/React/Firebase

### ISSUE THREAD

**Issue by filipecheverrya** [thr0w/idvogados#9]
Precisam de uma mão? Posso contribuir para o projeto, tenho tempo livre e conhecimento em ts, react e integração com firebase

**Comment by teintinu** [comment]
@fripley , preciso sim. Os fontes estão aí, fique à vontade pra contribuir. Estes dias estão bem corridos mas devo trabalhar um pouco mais no domingo a noite.
